config/routes.rb
Rails.application.routes.draw do
  resources :posts, :articles

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # get "/articles" => "articles#index"
  # get "/articles/new" => "articles#new"
  # get '/articles/:id' => 'articles#show'
  # Defines the root path route ("/")
  root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments, dependent: :destroy
  # has_many :long_comments, -> { where("length(body) > 30") }, class_name: 'Comment'

  validates :title, presence: true
  validates :body, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]

  def index
    @articles = Article.all.order :id
  end

  def show
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "Article was successfully created."}
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated"}
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @article.destroy!

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfuly deleted"}
    end
  end

  private
  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :body)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:name, :title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
    <div class="container">
        <div class="input-group mt-5">
            <%= form.label :title, class:"input-group-text" %>
            <%= form.text_field :title, class:"form-control" %>
        </div>
        <div class="input-group mt-3">
            <%= form.label :body, class:"input-group-text" %>
            <%= form.text_area :body, class:"form-control" %>
        </div>

        <div class="mt-3">
            <%= form.submit 'SUBMIT', class:"btn btn-primary" %>
        </div>
    </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render "form", article: @article %>
<br>
<br>

app/views/articles/index.html.erb
<table class="table table-hover table-dark mt-5">
    <thead>
        <tr>
            <th>ID</th>
            <th>Title</th>
            <th>Body</th>
            <th colspan=3>Actions</th>
        </tr>
    </thead>

    <tbody>
        <% @articles.each do |article| %>
        <tr>
            <td><%= article.id %></td>
            <td><%= article.title %></td>
            <td><%= article.body %></td>
            <td><%= link_to "Show", article %></td>
            <td><%= link_to "Edit", edit_article_path(article) %></td>
            <td><%= button_to "Delete", article, method: :delete, class:"btn btn-sm btn-danger" %></td>
        </tr>
        <% end %>
    </tbody>
</table>

<div>
    <%=link_to "New Article", new_article_path, class:"btn btn-primary" %>
</div>

app/views/articles/new.html.erb
<%= render "form", article: @article%>


<br>
<%= link_to "Back", articles_path, class:"btn btn-primary ms-2 mt-3" %>

app/views/articles/show.html.erb
<div class="container">
    <h2><%= @article.title %></h2>
    <p><%= @article.body %></p>
</div>
<br>
<%= link_to "Edit this article", edit_article_path, class: "btn btn-primary" %>
<%= button_to "Delete", @article, method: :delete, class: "btn btn-danger" %>

<br>
<br>
<%= link_to "Back", articles_path, class:"btn btn-primary"%>

app/views/layouts/_navbar.html.erb
<nav class="navbar bg-dark navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Blog</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to "Articles", articles_path, class: "nav-link"%>
        </li>

        <li class="nav-item">
          <%= link_to "Posts", posts_path, class: "nav-link"%>
        </li>
        
        <%# <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#drop" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" id="drop">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li> %>
        
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/_toast.html.erb
<div class="toast-container">
    <div class="toast" role="alert" aria-live="assertive" aria-atomic="true">
    <div class="toast-header">
        <%# <img src="..." class="rounded me-2" alt="..."> %>
        <strong class="me-auto">Alert</strong>
        <small>Just now..</small>
        <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
    </div>
    <div class="toast-body">
        <%= notice %>
    </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <style>
    /* Center toast horizontally */
    .toast {
      position: fixed;
      left: 50%;
      transform: translateX(-50%);
    }
    /* Prevent toast from adjusting other elements */
    .toast-container {
      position: fixed;
      top: 60px;
      left: 0;
      width: 100%;
      transform: translateY(-50%);
      z-index: 1050; /* Ensure toast appears above other elements */
    }
  </style>
  </head>

  <body>
    <%= render partial: "layouts/navbar" %>
    <%= render partial: "layouts/toast" %>
    <main class="container">
      <%= yield %>
    </main>
    <div class='ms-5 mt-5'>
    </div>
    <script>
      // Show toast if notice is present
      var notice = '<%= notice %>'.trim();
      if (notice) {
        $('.toast .toast-body').text(notice);
        $('.toast').toast('show');
      }
    </script>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>" class='card'>
  <div class="card-body">
    <div class="card-title">
      <strong>Name:</strong>
      <%= post.name %>
    </div>

    <p>
      <strong>Title:</strong>
      <%= post.title %>
    </p>

    <p>
      <strong>Content:</strong>
      <%= post.content %>
    </p>
  </div>
</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="container">
  <h1>Posts</h1>

  <div id="posts">
    <% @posts.each do |post| %>
      <%= render post %>
      <p>
        <%= link_to "Show this post", post %>
      </p>
    <% end %>
  </div>
</div>

<%= link_to "New post", new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>